name: Nightly Release

permissions:
  id-token: write
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  check-dependabot-commits:
    name: Check if dependabot commits exist
    outputs:
      isDependabot: ${{ steps.check-dependabot.outputs.dependabotExists }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if dependabot commits exist
        id: check-dependabot
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "dependabotExists=$(echo $GITHUB_CONTEXT | jq '.event.commits[].author | any(. == "dependabot[bot]")')" >> $GITHUB_OUTPUT

  nightly-checkmarx:
    needs: check-dependabot-commits
    if: ${{needs.check-dependabot-commits.outputs.isDependabot == 'false'}}
    uses: Checkmarx/ast-vscode-extension/.github/workflows/release-checkmarx.yml@main
    secrets: inherit

  nightly-project-ignite:
    needs: check-dependabot-commits
    if: ${{needs.check-dependabot-commits.outputs.isDependabot == 'false'}}
    uses: Checkmarx/ast-vscode-extension/.github/workflows/release-project-ignte.yml@main
    secrets: inherit
